version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          key: dep-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dep-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test